services:
  php-app:
    image : php:8.3-apache

    ports:
      - "8080:80"

    networks : 
      - back_net
      - front_net 
            
  mariadb:
    image: mariadb:11

    environment : 
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: site_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass

    networks :
      - back_net 

networks:
  front_net : 
    driver: bridge

  back_net : 
    driver: bridge
    internal: true